"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Lukas Guhse (https://sketchfab.com/guhselukas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scifi-character-model-fastlane-e04d4f8606854c858ec6771d044b5693
Title: SciFi Character Model - FastLane
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["Object080_08_-_Default_0"]: THREE.Mesh;
  };
  materials: {
    ["08_-_Default"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/charac.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[-21.386, 0, -27.254]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.063}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Object080_08_-_Default_0"].geometry}
            material={materials["08_-_Default"]}
            position={[-24.139, 24.624, -3.52]}
            rotation={[0, -0.262, 0]}
            scale={0.138}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/charac.glb");
